### ISSUE TITLE
Update FederatedStore Walkthrough

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-doc#192]
In 1.11.0, ChangeGraphAccess and GetAllGraphInfo were added to Gaffer. Add a section for these operations in the FederatedStore Walkthrough.

**Comment by n3101** [comment]
Given that Gaffer 2.0 will make breaking changes to FederatedStore, do this as part of that migration.

**Comment by GCHQDeveloper314** [comment]
The walkthrough needs to be updated for changes made to the Federated Store and associated operations in Gaffer 2.0 and also needs to be added to the Gaffer 2.0 docs - currently there is just a link to the v1 docs.

The walkthrough should be expanded to contain more details on configuration of the store using the REST API, rather than Java. This improved walkthrough will be part of the Administration Guide.

The "walkthrough" should also be renamed as a "guide" to be consistent with other parts of the Administration Guide.
