### ISSUE TITLE
Make v2docs release have a default version

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#304]
If a user does not enter a version to release, it should use the current latest version and overwrite that

**Comment by GCHQDeveloper314** [comment]
This can be done, but it's not all that simple to do. The deploy action would need to be changed so that it could get the latest version and then use that if a version wasn't entered.
I can see two approaches for getting the latest version:

- Using git tags.
- Using information from the `versions.json` file in the `gh-pages` branch.

**Comment by t92549** [comment]
Upon further reflection and conversation with @GCHQDeveloper314, we have decided that we should close this issue. This is because we want admins to be actively selecting a version of the docs to release, rather than it happening automatically, as this could actually increase possibility of mistake rather than decreasing it.
