### ISSUE TITLE
Add documentation for tinkerpop

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-doc#352]
We should document the new tinkerpop module within Gaffer. This includes basic getting started docs for users, as well as developer documentation. We should document how to download gremlin server, configure it to use gafferpop, and basic usage. We should also ensure the NamedOperationService is documented.

**Comment by GCHQDeveloper314** [comment]
The tinkerpop module `README` in gchq/Gaffer should be used as the basis for this. The content from that file should be migrated into this repo as part of this ticket.

**Comment by GCHQDeveloper314** [comment]
The Gremlin/Tinkerpop module configuration has been [documented on this page](https://gchq.github.io/gaffer-doc/latest/administration-guide/gaffer-deployment/gremlin.html). This was done against #451.
How a user can query using Gremlin has [been covered here](https://gchq.github.io/gaffer-doc/latest/user-guide/query/gremlin/gremlin.html). This was done against #454.

The work above could have all been done against this issue. The only area which is not yet covered is the NamedOperationService. Instead of rescoping this issue I will raise a new issue to cover that.
